name: update-snapshots
on:
  # will send emails to last editor of this cron syntax (distroless-bot)
  schedule:
    - cron:  '35 8 * * *'
  
permissions:
  contents: read
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Run update script
      run: ./updateWorkspaceSnapshots.sh
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@284f54f989303d2699d373481a0cfa13ad5a6666 # v5.0.1
      with:
        token: ${{ secrets.ACTIONS_TOKEN }}
        commit-message: "Bumping packages to latest stable versions"
        author: "Distroless Bot <distroless-bot@google.com>"
        title: "Bumping packages to latest stable versions"
        body: "Bumping packages to latest stable versions"
        branch: "update-snapshots"
